version: "3.9"

services:
  backend:
    build:
      context: ./bookly-backend
    ports:
      - "8000:8000"
    env_file:
      - ./bookly-backend/.env
    restart: always

  frontend:
    build:
      context: ./bookly-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always